workflows:
  build-calculator:
    name: Cordova Android Build
    max_build_duration: 60
    environment:
      vars:
        CORDOVA_ANDROID_VERSION: "12.0.0"
      node: 18.16.0
    scripts:
      - name: Install Cordova & Dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Build Cordova App
        script: |
          cordova platform add android
          cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - zahammed991@gmail.com
