



workflows:
  android-workflow:
    name: Cordova Android Build
    environment:
      vars:
        PACKAGE_NAME: "com.example.calculator"
      node: latest
    scripts:
      - npm install -g cordova
      - cordova platform add android
      - cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - zahammed991@gmail.com

