workflows:
  cordova-android:
    name: Cordova Android Build
    environment:
      node: 18
      java: 17
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Add Android Platform
        script: |
          cordova platform rm android || true
          cordova platform add android
      - name: Build Android App
        script: |
          cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/**/*.apk
